config/routes.rb
Rails.application.routes.draw do

  resources :borders
  resources :countries

  resources :countries do
      get 'listBorderCountry'
      get 'translimite'
  end

  root 'countries#index'

end

app/models/border.rb
class Border < ActiveRecord::Base
end

app/models/country.rb
class Country < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/borders_controller.rb
class BordersController < ApplicationController
  before_action :set_border, only: [:show, :edit, :update, :destroy]

  # GET /borders
  # GET /borders.json
  def index
    @borders = Border.all
    @countries = Country.all
  end

  # GET /borders/1
  # GET /borders/1.json
  def show
    @countries = Country.all
  end

  # GET /borders/new
  def new
    @border = Border.new
  end

  # GET /borders/1/edit
  def edit
  end

  # POST /borders
  # POST /borders.json
  def create
    @border = Border.new(border_params)

    respond_to do |format|
      if @border.save
        format.html { redirect_to @border, notice: 'Border was successfully created.' }
        format.json { render :show, status: :created, location: @border }
      else
        format.html { render :new }
        format.json { render json: @border.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /borders/1
  # PATCH/PUT /borders/1.json
  def update
    respond_to do |format|
      if @border.update(border_params)
        format.html { redirect_to @border, notice: 'Border was successfully updated.' }
        format.json { render :show, status: :ok, location: @border }
      else
        format.html { render :edit }
        format.json { render json: @border.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /borders/1
  # DELETE /borders/1.json
  def destroy
    @border.destroy
    respond_to do |format|
      format.html { redirect_to borders_url, notice: 'Border was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_border
      @border = Border.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def border_params
      params.require(:border).permit(:country1, :country2)
    end
end

app/controllers/countries_controller.rb
class CountriesController < ApplicationController
  before_action :set_country, only: [:show, :edit, :update, :destroy]

  # GET /countries
  # GET /countries.json
  def index
    @countries = Country.all
  end

  # GET /countries/1
  # GET /countries/1.json
  def show
  end

  # GET /countries/new
  def new
    @country = Country.new
  end

  # GET /countries/1/edit
  def edit
  end

  # GET /countries/1/listBorderCountry
  def listBorderCountry
    @country = Country.find(params[:country_id])
    @borders = Border.where("country1 = #{params[:country_id]} or country2 = #{params[:country_id]}")
    @responseBorders = Array.new
    j = 0
    @borders.each do |border|
      if border.country1 == params[:country_id].to_i
        @responseBorders[j] = Country.find(border.country2).name
        j = j + 1
      end
      if border.country2 == params[:country_id].to_i
        @responseBorders[j] = Country.find(border.country1).name
        j = j + 1
      end
    end

  end

  # GET /countries/1/translimite
  def translimite
    @country1 = Country.find(params[:country1]).name
    @country2 = Country.find(params[:country2]).name
    @borders11 = Border.where("country1 = #{params[:country1]}")
    @borders12 = Border.where("country2 = #{params[:country1]}")
    borders21 = Border.where("country1 = #{params[:country2]}")
    borders22 = Border.where("country2 = #{params[:country2]}")
    @borderResponse = Array.new
    @b1 = Array.new
    b2 = Array.new
    j = 0
    k = 0

    @borders11.each do |border|
      @b1[j] = border.country2
      j = j + 1
    end

    @borders12.each do |border|
      @b1[j] = border.country1
      j = j + 1
    end

    j=0
    borders21.each do |border|
      b2[j] = border.country2
      j = j + 1
    end

    borders22.each do |border|
      b2[j] = border.country1
      j = j + 1
    end

    for i in 0..@b1.size
      for l in 0..b2.size
        if @b1[i] == b2[l]
          @borderResponse[k] = @b1[i]
          k = k + 1
        end
      end
    end
    @borderResponse = Country.find(@borderResponse)
  end

  # POST /countries
  # POST /countries.json
  def create
    @country = Country.new(country_params)

    respond_to do |format|
      if @country.save
        format.html { redirect_to @country, notice: 'Country was successfully created.' }
        format.json { render :show, status: :created, location: @country }
      else
        format.html { render :new }
        format.json { render json: @country.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /countries/1
  # PATCH/PUT /countries/1.json
  def update
    respond_to do |format|
      if @country.update(country_params)
        format.html { redirect_to @country, notice: 'Country was successfully updated.' }
        format.json { render :show, status: :ok, location: @country }
      else
        format.html { render :edit }
        format.json { render json: @country.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /countries/1
  # DELETE /countries/1.json
  def destroy
    @country.destroy
    respond_to do |format|
      format.html { redirect_to countries_url, notice: 'Country was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_country
      @country = Country.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def country_params
      params.require(:country).permit(:name, :extension)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/borders_helper.rb
module BordersHelper
end

app/helpers/countries_helper.rb
module CountriesHelper
end

app/views/borders/_form.html.erb
<%= form_for(@border) do |f| %>
  <% if @border.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@border.errors.count, "error") %> prohibited this border from being saved:</h2>

      <ul>
      <% @border.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :country1 %><br>
    <%= f.number_field :country1 %>
  </div>
  <div class="field">
    <%= f.label :country2 %><br>
    <%= f.number_field :country2 %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/borders/edit.html.erb
<h1>Editing Border</h1>

<%= render 'form' %>

<%= link_to 'Show', @border %> |
<%= link_to 'Back', borders_path %>

app/views/borders/index.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Countries', countries_path %>

<h1>Listing Borders</h1>

<table>
  <thead>
    <tr>
      <th>Country1</th>
      <th>Name</th>
      <th>Country2</th>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @borders.each do |border| %>
      <tr>
        <td><%= border.country1 %></td>
        <td><%= @countries[border.country1-1].name%></td>
        <td><%= border.country2 %></td>
        <td><%= @countries[border.country2-1].name%></td>
        <td><%= link_to 'Show', border %></td>
        <td><%= link_to 'Edit', edit_border_path(border) %></td>
        <td><%= link_to 'Destroy', border, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Border', new_border_path %>

app/views/borders/new.html.erb
<h1>New Border</h1>

<%= render 'form' %>

<%= link_to 'Back', borders_path %>

app/views/borders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Country1:</strong>
  <%= @border.country1 %><br>
  <%= @countries[@border.country1-1].name%>
</p>

<p>
  <strong>Country2:</strong>
  <%= @border.country2 %><br>
  <%= @countries[@border.country2-1].name%>
</p>

<%= link_to 'Edit', edit_border_path(@border) %> |
<%= link_to 'Back', borders_path %>

app/views/countries/_form.html.erb
<%= form_for(@country) do |f| %>
  <% if @country.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@country.errors.count, "error") %> prohibited this country from being saved:</h2>

      <ul>
      <% @country.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :extension %><br>
    <%= f.number_field :extension %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/countries/edit.html.erb
<h1>Editing Country</h1>

<%= render 'form' %>

<%= link_to 'Show', @country %> |
<%= link_to 'Back', countries_path %>

app/views/countries/index.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Borders', borders_path %>

<h1>Listing Countries</h1>

<table>
  <thead>
    <tr>
      <th>Id</th>
      <th>Name</th>
      <th>Extension</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @countries.each do |country| %>
      <tr>
        <td><%= country.id %></td>
        <td><%= country.name %></td>
        <td><%= country.extension %></td>
        <td><%= link_to 'Show', country %></td>
        <td><%= link_to 'Edit', edit_country_path(country) %></td>
        <td><%= link_to 'Destroy', country, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <td><%= link_to "Show borders", country_listBorderCountry_path(country) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<form accept-charset="UTF-8" action="<%= country_translimite_path(2) %>" method="get">
  Country1:<br>
  <input name="country1" type="number"/><br>
  Country2:<br>
  <input name="country2" type="number"/><br><br>
  <input type="submit" value"Translimite"><br><br>
</form>

<%= link_to 'New Country', new_country_path %>

app/views/countries/listBorderCountry.html.erb
<%= link_to "Countries", countries_path %>
<h1>List of borders</h1>
<strong>The bordering countries of <%= @country['name'] %> are:</strong>
<br><br>
<% @responseBorders.each do |country| %>
	<%= country %><br>
<% end %>

app/views/countries/new.html.erb
<h1>New Country</h1>

<%= render 'form' %>

<%= link_to 'Back', countries_path %>

app/views/countries/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @country.name %>
</p>

<p>
  <strong>Extension:</strong>
  <%= @country.extension %>
</p>

<%= link_to 'Edit', edit_country_path(@country) %> |
<%= link_to 'Back', countries_path %>

app/views/countries/translimite.html.erb
<%= link_to "Countries", countries_path %><br>
<strong>Countries between <%= @country1 %> and <%= @country2 %>:</strong><br>
<% @borderResponse.each do |country| %>
	<%= country.name %><br>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SIpaises</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>